from django.db import models
# Create your models here.


class Settings(models.Model):
    printer_ip = models.GenericIPAddressField()
    printer_autoprint = models.BooleanField()
    current_comp_id = models.PositiveSmallIntegerField()
    version = models.PositiveSmallIntegerField()


class Competition(models.Model):
    comp_name = models.CharField(max_length=50)
    comp_type = models.PositiveSmallIntegerField()
    comp_data = models.CharField(max_length=3000)


class Group(models.Model):
    group_name = models.CharField(max_length=20)
    group_seq = models.CharField(max_length=200)
    #group_competition_id = models.PositiveSmallIntegerField()
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)


class Runner(models.Model):
    runner_sn = models.PositiveIntegerField()
    #runner_competition_id = models.PositiveSmallIntegerField()
    #runner_group_id = models.PositiveIntegerField()
    runner_name = models.CharField(max_length=50)
    runner_club = models.CharField(max_length=30)
    runner_coach = models.CharField(max_length=50)
    runner_skill = models.CharField(max_length=20)
    runner_state = models.CharField(max_length=30)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)


class Wrist(models.Model):
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)
    #wrist_competition_id = models.PositiveSmallIntegerField()
    wrist_sn = models.PositiveSmallIntegerField()
    wrist_firmware = models.PositiveSmallIntegerField()
    wrist_voltage = models.PositiveSmallIntegerField()
#    wrist_passed = models.BooleanField()
#    wrist_total_time = models.PositiveIntegerField()
#    wrist_points = models.PositiveSmallIntegerField()
    wrist_seq = models.CharField(max_length=1024)
    wrist_punches = models.CharField(max_length=1800)
    # wrist_cp0 = models.PositiveIntegerField()
    # wrist_cp1 = models.PositiveIntegerField()
    # wrist_cp2 = models.PositiveIntegerField()
    # wrist_cp3 = models.PositiveIntegerField()
    # wrist_cp4 = models.PositiveIntegerField()
    # wrist_cp5 = models.PositiveIntegerField()
    # wrist_cp6 = models.PositiveIntegerField()
    # wrist_cp7 = models.PositiveIntegerField()
    # wrist_cp8 = models.PositiveIntegerField()
    # wrist_cp9 = models.PositiveIntegerField()
    # wrist_cp10 = models.PositiveIntegerField()
    # wrist_cp11 = models.PositiveIntegerField()
    # wrist_cp12 = models.PositiveIntegerField()
    # wrist_cp13 = models.PositiveIntegerField()
    # wrist_cp14 = models.PositiveIntegerField()
    # wrist_cp15 = models.PositiveIntegerField()
    # wrist_cp16 = models.PositiveIntegerField()
    # wrist_cp17 = models.PositiveIntegerField()
    # wrist_cp18 = models.PositiveIntegerField()
    # wrist_cp19 = models.PositiveIntegerField()
    # wrist_cp20 = models.PositiveIntegerField()
    # wrist_cp21 = models.PositiveIntegerField()
    # wrist_cp22 = models.PositiveIntegerField()
    # wrist_cp23 = models.PositiveIntegerField()
    # wrist_cp24 = models.PositiveIntegerField()
    # wrist_cp25 = models.PositiveIntegerField()
    # wrist_cp26 = models.PositiveIntegerField()
    # wrist_cp27 = models.PositiveIntegerField()
    # wrist_cp28 = models.PositiveIntegerField()
    # wrist_cp29 = models.PositiveIntegerField()
    # wrist_cp30 = models.PositiveIntegerField()
    # wrist_cp31 = models.PositiveIntegerField()
    # wrist_cp32 = models.PositiveIntegerField()
    # wrist_cp33 = models.PositiveIntegerField()
    # wrist_cp34 = models.PositiveIntegerField()
    # wrist_cp35 = models.PositiveIntegerField()
    # wrist_cp36 = models.PositiveIntegerField()
    # wrist_cp37 = models.PositiveIntegerField()
    # wrist_cp38 = models.PositiveIntegerField()
    # wrist_cp39 = models.PositiveIntegerField()
    # wrist_cp40 = models.PositiveIntegerField()
    # wrist_cp41 = models.PositiveIntegerField()
    # wrist_cp42 = models.PositiveIntegerField()
    # wrist_cp43 = models.PositiveIntegerField()
    # wrist_cp44 = models.PositiveIntegerField()
    # wrist_cp45 = models.PositiveIntegerField()
    # wrist_cp46 = models.PositiveIntegerField()
    # wrist_cp47 = models.PositiveIntegerField()
    # wrist_cp48 = models.PositiveIntegerField()
    # wrist_cp49 = models.PositiveIntegerField()
    # wrist_cp50 = models.PositiveIntegerField()
    # wrist_cp51 = models.PositiveIntegerField()
    # wrist_cp52 = models.PositiveIntegerField()
    # wrist_cp53 = models.PositiveIntegerField()
    # wrist_cp54 = models.PositiveIntegerField()
    # wrist_cp55 = models.PositiveIntegerField()
    # wrist_cp56 = models.PositiveIntegerField()
    # wrist_cp57 = models.PositiveIntegerField()
    # wrist_cp58 = models.PositiveIntegerField()
    # wrist_cp59 = models.PositiveIntegerField()
    # wrist_cp60 = models.PositiveIntegerField()
    # wrist_cp61 = models.PositiveIntegerField()
    # wrist_cp62 = models.PositiveIntegerField()
    # wrist_cp63 = models.PositiveIntegerField()
    # wrist_cp64 = models.PositiveIntegerField()
    # wrist_cp65 = models.PositiveIntegerField()
    # wrist_cp66 = models.PositiveIntegerField()
    # wrist_cp67 = models.PositiveIntegerField()
    # wrist_cp68 = models.PositiveIntegerField()
    # wrist_cp69 = models.PositiveIntegerField()
    # wrist_cp70 = models.PositiveIntegerField()
    # wrist_cp71 = models.PositiveIntegerField()
    # wrist_cp72 = models.PositiveIntegerField()
    # wrist_cp73 = models.PositiveIntegerField()
    # wrist_cp74 = models.PositiveIntegerField()
    # wrist_cp75 = models.PositiveIntegerField()
    # wrist_cp76 = models.PositiveIntegerField()
    # wrist_cp77 = models.PositiveIntegerField()
    # wrist_cp78 = models.PositiveIntegerField()
    # wrist_cp79 = models.PositiveIntegerField()
    # wrist_cp80 = models.PositiveIntegerField()
    # wrist_cp81 = models.PositiveIntegerField()
    # wrist_cp82 = models.PositiveIntegerField()
    # wrist_cp83 = models.PositiveIntegerField()
    # wrist_cp84 = models.PositiveIntegerField()
    # wrist_cp85 = models.PositiveIntegerField()
    # wrist_cp86 = models.PositiveIntegerField()
    # wrist_cp87 = models.PositiveIntegerField()
    # wrist_cp88 = models.PositiveIntegerField()
    # wrist_cp89 = models.PositiveIntegerField()
    # wrist_cp90 = models.PositiveIntegerField()
    # wrist_cp91 = models.PositiveIntegerField()
    # wrist_cp92 = models.PositiveIntegerField()
    # wrist_cp93 = models.PositiveIntegerField()
    # wrist_cp94 = models.PositiveIntegerField()
    # wrist_cp95 = models.PositiveIntegerField()
    # wrist_cp96 = models.PositiveIntegerField()
    # wrist_cp97 = models.PositiveIntegerField()
    # wrist_cp98 = models.PositiveIntegerField()
    # wrist_cp99 = models.PositiveIntegerField()
    # wrist_cp100 = models.PositiveIntegerField()
    # wrist_cp101 = models.PositiveIntegerField()
    # wrist_cp102 = models.PositiveIntegerField()
    # wrist_cp103 = models.PositiveIntegerField()
    # wrist_cp104 = models.PositiveIntegerField()
    # wrist_cp105 = models.PositiveIntegerField()
    # wrist_cp106 = models.PositiveIntegerField()
    # wrist_cp107 = models.PositiveIntegerField()
    # wrist_cp108 = models.PositiveIntegerField()
    # wrist_cp109 = models.PositiveIntegerField()
    # wrist_cp110 = models.PositiveIntegerField()
    # wrist_cp111 = models.PositiveIntegerField()
    # wrist_cp112 = models.PositiveIntegerField()
    # wrist_cp113 = models.PositiveIntegerField()
    # wrist_cp114 = models.PositiveIntegerField()
    # wrist_cp115 = models.PositiveIntegerField()
    # wrist_cp116 = models.PositiveIntegerField()
    # wrist_cp117 = models.PositiveIntegerField()
    # wrist_cp118 = models.PositiveIntegerField()
    # wrist_cp119 = models.PositiveIntegerField()
    # wrist_cp120 = models.PositiveIntegerField()
    # wrist_cp121 = models.PositiveIntegerField()
    # wrist_cp122 = models.PositiveIntegerField()
    # wrist_cp123 = models.PositiveIntegerField()
    # wrist_cp124 = models.PositiveIntegerField()
    # wrist_cp125 = models.PositiveIntegerField()
    # wrist_cp126 = models.PositiveIntegerField()
    # wrist_cp127 = models.PositiveIntegerField()
    # wrist_cp128 = models.PositiveIntegerField()
    # wrist_cp129 = models.PositiveIntegerField()
    # wrist_cp130 = models.PositiveIntegerField()
    # wrist_cp131 = models.PositiveIntegerField()
    # wrist_cp132 = models.PositiveIntegerField()
    # wrist_cp133 = models.PositiveIntegerField()
    # wrist_cp134 = models.PositiveIntegerField()
    # wrist_cp135 = models.PositiveIntegerField()
    # wrist_cp136 = models.PositiveIntegerField()
    # wrist_cp137 = models.PositiveIntegerField()
    # wrist_cp138 = models.PositiveIntegerField()
    # wrist_cp139 = models.PositiveIntegerField()
    # wrist_cp140 = models.PositiveIntegerField()
    # wrist_cp141 = models.PositiveIntegerField()
    # wrist_cp142 = models.PositiveIntegerField()
    # wrist_cp143 = models.PositiveIntegerField()
    # wrist_cp144 = models.PositiveIntegerField()
    # wrist_cp145 = models.PositiveIntegerField()
    # wrist_cp146 = models.PositiveIntegerField()
    # wrist_cp147 = models.PositiveIntegerField()
    # wrist_cp148 = models.PositiveIntegerField()
    # wrist_cp149 = models.PositiveIntegerField()
    # wrist_cp150 = models.PositiveIntegerField()
    # wrist_cp151 = models.PositiveIntegerField()
    # wrist_cp152 = models.PositiveIntegerField()
    # wrist_cp153 = models.PositiveIntegerField()
    # wrist_cp154 = models.PositiveIntegerField()
    # wrist_cp155 = models.PositiveIntegerField()
    # wrist_cp156 = models.PositiveIntegerField()
    # wrist_cp157 = models.PositiveIntegerField()
    # wrist_cp158 = models.PositiveIntegerField()
    # wrist_cp159 = models.PositiveIntegerField()
    # wrist_cp160 = models.PositiveIntegerField()
    # wrist_cp161 = models.PositiveIntegerField()
    # wrist_cp162 = models.PositiveIntegerField()
    # wrist_cp163 = models.PositiveIntegerField()
    # wrist_cp164 = models.PositiveIntegerField()
    # wrist_cp165 = models.PositiveIntegerField()
    # wrist_cp166 = models.PositiveIntegerField()
    # wrist_cp167 = models.PositiveIntegerField()
    # wrist_cp168 = models.PositiveIntegerField()
    # wrist_cp169 = models.PositiveIntegerField()
    # wrist_cp170 = models.PositiveIntegerField()
    # wrist_cp171 = models.PositiveIntegerField()
    # wrist_cp172 = models.PositiveIntegerField()
    # wrist_cp173 = models.PositiveIntegerField()
    # wrist_cp174 = models.PositiveIntegerField()
    # wrist_cp175 = models.PositiveIntegerField()
    # wrist_cp176 = models.PositiveIntegerField()
    # wrist_cp177 = models.PositiveIntegerField()
    # wrist_cp178 = models.PositiveIntegerField()
    # wrist_cp179 = models.PositiveIntegerField()
    # wrist_cp180 = models.PositiveIntegerField()
    # wrist_cp181 = models.PositiveIntegerField()
    # wrist_cp182 = models.PositiveIntegerField()
    # wrist_cp183 = models.PositiveIntegerField()
    # wrist_cp184 = models.PositiveIntegerField()
    # wrist_cp185 = models.PositiveIntegerField()
    # wrist_cp186 = models.PositiveIntegerField()
    # wrist_cp187 = models.PositiveIntegerField()
    # wrist_cp188 = models.PositiveIntegerField()
    # wrist_cp189 = models.PositiveIntegerField()
    # wrist_cp190 = models.PositiveIntegerField()
    # wrist_cp191 = models.PositiveIntegerField()
    # wrist_cp192 = models.PositiveIntegerField()
    # wrist_cp193 = models.PositiveIntegerField()
    # wrist_cp194 = models.PositiveIntegerField()
    # wrist_cp195 = models.PositiveIntegerField()
    # wrist_cp196 = models.PositiveIntegerField()
    # wrist_cp197 = models.PositiveIntegerField()
    # wrist_cp198 = models.PositiveIntegerField()
    # wrist_cp199 = models.PositiveIntegerField()
    # wrist_cp200 = models.PositiveIntegerField()
    # wrist_cp201 = models.PositiveIntegerField()
    # wrist_cp202 = models.PositiveIntegerField()
    # wrist_cp203 = models.PositiveIntegerField()
    # wrist_cp204 = models.PositiveIntegerField()
    # wrist_cp205 = models.PositiveIntegerField()
    # wrist_cp206 = models.PositiveIntegerField()
    # wrist_cp207 = models.PositiveIntegerField()
    # wrist_cp208 = models.PositiveIntegerField()
    # wrist_cp209 = models.PositiveIntegerField()
    # wrist_cp210 = models.PositiveIntegerField()
    # wrist_cp211 = models.PositiveIntegerField()
    # wrist_cp212 = models.PositiveIntegerField()
    # wrist_cp213 = models.PositiveIntegerField()
    # wrist_cp214 = models.PositiveIntegerField()
    # wrist_cp215 = models.PositiveIntegerField()
    # wrist_cp216 = models.PositiveIntegerField()
    # wrist_cp217 = models.PositiveIntegerField()
    # wrist_cp218 = models.PositiveIntegerField()
    # wrist_cp219 = models.PositiveIntegerField()
    # wrist_cp220 = models.PositiveIntegerField()
    # wrist_cp221 = models.PositiveIntegerField()
    # wrist_cp222 = models.PositiveIntegerField()
    # wrist_cp223 = models.PositiveIntegerField()
    # wrist_cp224 = models.PositiveIntegerField()
    # wrist_cp225 = models.PositiveIntegerField()
    # wrist_cp226 = models.PositiveIntegerField()
    # wrist_cp227 = models.PositiveIntegerField()
    # wrist_cp228 = models.PositiveIntegerField()
    # wrist_cp229 = models.PositiveIntegerField()
    # wrist_cp230 = models.PositiveIntegerField()
    # wrist_cp231 = models.PositiveIntegerField()
    # wrist_cp232 = models.PositiveIntegerField()
    # wrist_cp233 = models.PositiveIntegerField()
    # wrist_cp234 = models.PositiveIntegerField()
    # wrist_cp235 = models.PositiveIntegerField()
    # wrist_cp236 = models.PositiveIntegerField()
    # wrist_cp237 = models.PositiveIntegerField()
    # wrist_cp238 = models.PositiveIntegerField()
    # wrist_cp239 = models.PositiveIntegerField()
    # wrist_cp240 = models.PositiveIntegerField()
    # wrist_cp241 = models.PositiveIntegerField()
    # wrist_cp242 = models.PositiveIntegerField()
    # wrist_cp243 = models.PositiveIntegerField()
    # wrist_cp244 = models.PositiveIntegerField()
    # wrist_cp245 = models.PositiveIntegerField()
    # wrist_cp246 = models.PositiveIntegerField()
    # wrist_cp247 = models.PositiveIntegerField()
    # wrist_cp248 = models.PositiveIntegerField()
    # wrist_cp249 = models.PositiveIntegerField()
    # wrist_cp250 = models.PositiveIntegerField()
    # wrist_cp251 = models.PositiveIntegerField()
    # wrist_cp252 = models.PositiveIntegerField()
    # wrist_cp253 = models.PositiveIntegerField()
    # wrist_cp254 = models.PositiveIntegerField()
