# Generated by Django 3.2.3 on 2021-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0002_alter_competition_comp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='comp_type',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
