# Generated by Django 3.2.3 on 2021-06-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0003_alter_competition_comp_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
