# Generated by Django 3.2.3 on 2021-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0004_rename_groups_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_ip', models.GenericIPAddressField()),
                ('current_comp_id', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='comp_data',
            field=models.CharField(default='description', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_competition_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
