# Generated by Django 3.2.3 on 2021-06-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0005_auto_20210617_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='printer_autoprint',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
