# Generated by Django 3.2.3 on 2021-06-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0010_competition_group_runner_settings_wrist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Wrist',
        ),
    ]
