# Generated by Django 3.2.3 on 2021-07-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0012_competition_group_runner_settings_wrist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrist',
            name='wrist_passed',
        ),
        migrations.RemoveField(
            model_name='wrist',
            name='wrist_points',
        ),
        migrations.RemoveField(
            model_name='wrist',
            name='wrist_total_time',
        ),
    ]
