# Generated by Django 3.2.3 on 2021-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0013_auto_20210703_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer', models.CharField(max_length=50)),
                ('current_competition', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
