# Generated by Django 3.2.3 on 2021-09-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0014_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
