# Generated by Django 3.2.3 on 2021-09-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0015_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminer.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runner',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminer.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrist',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminer.competition'),
            preserve_default=False,
        ),
    ]
