# Generated by Django 3.2.3 on 2021-09-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0016_auto_20210906_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_competition_id',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='runner_competition_id',
        ),
        migrations.RemoveField(
            model_name='runner',
            name='runner_group_id',
        ),
        migrations.RemoveField(
            model_name='wrist',
            name='wrist_competition_id',
        ),
    ]
