# Generated by Django 3.2.3 on 2021-09-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminer', '0017_auto_20210906_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminer.competition'),
            preserve_default=False,
        ),
    ]
